[project]
name = "basic"
version = "0.2.0"
description = "BASIC language interpreter"
authors = [
    {name = "Yitzchak Gale",email = "gale@sefer.org"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "tdp-parser>=0.2.0,<0.3.0",
]

[project.urls]
Repository = "https://github.com/ygale/basic"

[project.scripts]
basic = "basic.basic:main"

[tool.poetry]
packages = [{include = "basic", from = "src"}]
include = ["src/basic/py.typed"]

[tool.poetry.group.dev.dependencies]
pytest = ">=8.4.1,<9.0.0"
pytest-cov = ">=5.0.0,<6.0.0"

[tool.pytest.ini_options]
addopts = "-q --cov=basic --cov-branch --cov-report=term-missing:skip-covered"
testpaths = ["tests"]

[tool.coverage.run]
source = ["src/basic"]
branch = true
parallel = true

[tool.coverage.report]
omit = [
  "tests/*",
]
show_missing = true
skip_covered = true

[tool.mypy]
python_version = "3.12"
namespace_packages = true
files = ["src"] # default target
mypy_path = ["src"] # tell mypy where to find code

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
