[project]
name = "basic"
version = "0.1.0"
description = "BASIC language interpreter"
authors = [
    {name = "Yitzchak Gale",email = "gale@sefer.org"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.poetry]
packages = [{include = "basic", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.12"
parserlib = { path = "../parserlib", develop = true }

[tool.poetry.group.dev.dependencies]
pytest = ">=8.4.1,<9.0.0"
pytest-cov = ">=5.0.0,<6.0.0"

[tool.pytest.ini_options]
addopts = "-q --cov=basic --cov-branch --cov-report=term-missing:skip-covered"
testpaths = ["tests"]

[tool.coverage.run]
source = ["src/basic"]
branch = true
parallel = true

[tool.coverage.report]
omit = [
  "tests/*",
]
show_missing = true
skip_covered = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
